(define (problem hanoi-problem)
  (:domain HANOI)
  (:objects A B C D PIC1 PIC2 PIC3)
  (:init 
    (handEmpty)
    (isPic PIC1) (isPic PIC2) (isPic PIC3)
    (isEmpty PIC2) (isEmpty PIC3)
    (isDisque A) (isDisque B) (isDisque C) (isDisque D)
    (largerThan B A) (largerThan C B) (largerThan C A) (largerThan D C) (largerThan D B) (largerThan D A)
    (on A B)(on B C)(on C D)(on D PIC1)
    (clear A)
  )
  (:goal (and(on A B)(on B C)(on C D)(on D PIC3)) )
)